name: google_login_app
description: "SafeSteps – varna navigacija ponoči."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Lokalizacija
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2

  # Ikone in izgled
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  animate_do: ^3.0.2
  # Firebase
  firebase_core_platform_interface: ^5.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.6.7

  # Mapa in lokacija
  google_maps_flutter: ^2.5.0
  location: ^8.0.0
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  fluttertoast: ^8.2.2
  http: ^1.1.0
  latlong2: ^0.9.0
  flutter_dotenv: ^5.1.0
  dio: ^5.8.0+1
  flutter_polyline_points: ^2.1.0
  url_launcher: ^6.2.5
  fl_chart: ^0.63.0
  collection: ^1.18.0
  lib: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.14.3
  mockito: ^5.4.0
  build_runner: ^2.4.0
  fake_async: ^1.3.1
  test: ^1.24.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/lang/

# Lokalizacijska konfiguracija (IZVEN `flutter:` bloka!)
localizations:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  preferred-supported-locales:
    - en
    - sl

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/location.png"
  adaptive_icon_background: "#00000000"
  adaptive_icon_foreground: "assets/icon/location.png"
