// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5m_Sx1mndsL-IS4xJ2ZtXMuwYQj19mi4',
    appId: '1:872829523999:web:cf6a95dbcf209cb13e9d2a',
    messagingSenderId: '872829523999',
    projectId: 'safe-steps-ba9bb',
    authDomain: 'safe-steps-ba9bb.firebaseapp.com',
    storageBucket: 'safe-steps-ba9bb.firebasestorage.app',
    measurementId: 'G-8192H3FLWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt3nGT0ew4B_tIgFa0oMQ8xA5PUuTuhEw',
    appId: '1:872829523999:android:e8ee73a730c946ff3e9d2a',
    messagingSenderId: '872829523999',
    projectId: 'safe-steps-ba9bb',
    storageBucket: 'safe-steps-ba9bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQhztK1kPfNEfPB0i7rpzanknbhnlvCaQ',
    appId: '1:872829523999:ios:0a1e06d27db5c6a03e9d2a',
    messagingSenderId: '872829523999',
    projectId: 'safe-steps-ba9bb',
    storageBucket: 'safe-steps-ba9bb.firebasestorage.app',
    androidClientId:
        '872829523999-hek68of054vbedkj4t554mi14mf7hu2d.apps.googleusercontent.com',
    iosClientId:
        '872829523999-43sbmrkmt8ch99oe77r00uvaliiafkoe.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQhztK1kPfNEfPB0i7rpzanknbhnlvCaQ',
    appId: '1:872829523999:ios:0a1e06d27db5c6a03e9d2a',
    messagingSenderId: '872829523999',
    projectId: 'safe-steps-ba9bb',
    storageBucket: 'safe-steps-ba9bb.firebasestorage.app',
    androidClientId:
        '872829523999-hek68of054vbedkj4t554mi14mf7hu2d.apps.googleusercontent.com',
    iosClientId:
        '872829523999-43sbmrkmt8ch99oe77r00uvaliiafkoe.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleLoginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5m_Sx1mndsL-IS4xJ2ZtXMuwYQj19mi4',
    appId: '1:872829523999:web:ab0a9680fa1cde253e9d2a',
    messagingSenderId: '872829523999',
    projectId: 'safe-steps-ba9bb',
    authDomain: 'safe-steps-ba9bb.firebaseapp.com',
    storageBucket: 'safe-steps-ba9bb.firebasestorage.app',
    measurementId: 'G-2XMTEHVDPY',
  );
}
