name: Flutter Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup .env file
        run: |
          echo "ORS_API_KEY=${{ secrets.ORS_API_KEY }}" > .env

      - name: Setup env.dart
        run: |
          echo "const String googleAPIKey = '${{ secrets.GOOGLE_API_KEY }}';" > lib/env.dart

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: 'stable'

      - name: Check Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Generate localization files
        run: flutter gen-l10n

      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: flutter test --coverage