name: Flutter Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      # Setup Java for Firebase emulators
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      
      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
      
      # Get dependencies
      - name: Install dependencies
        run: flutter pub get
      
      # Cache dependencies to speed up builds
      - uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            **/build/
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      
      # Run analyzer
      - name: Analyze code
        run: flutter analyze
      
      # Combined test running for better efficiency
      - name: Run all tests
        run: |
          flutter test --test-randomize-ordering-seed random
          flutter test test/map_screen_test.dart
          flutter test test/login_screen_test.dart
          flutter test test/auth_service_test.dart
          flutter test test/directions_repository_test.dart
          flutter test test/osm_repository_test.dart
          flutter test test/directions_model_test.dart
      
      # Run with coverage
      - name: Generate coverage report
        if: always()
        run: |
          flutter test --coverage
          # Generate HTML coverage report (optional)
          genhtml coverage/lcov.info -o coverage/html
      
      # Upload coverage results using updated v4
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            coverage/lcov.info
            coverage/html/
            test/**/output.xml